/**
 * Logic Mill Api
 * This is the API of the Logic Mill project
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DocWrapper from './DocWrapper';

/**
* The BulkDocumentRequest model module.
* @module model/BulkDocumentRequest
* @version 0.0.0
*/
export default class BulkDocumentRequest {
    /**
    * Constructs a new <code>BulkDocumentRequest</code>.
    * @alias module:model/BulkDocumentRequest
    * @class
    * @param data {Array.<module:model/DocWrapper>} 
    */

    constructor(data) {
        
        
        this['data'] = data;
        
    }

    /**
    * Constructs a <code>BulkDocumentRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BulkDocumentRequest} obj Optional instance to populate.
    * @return {module:model/BulkDocumentRequest} The populated <code>BulkDocumentRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BulkDocumentRequest();
                        
            
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [DocWrapper]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/DocWrapper>} data
    */
    'data' = undefined;




}
