/**
 * Logic Mill Api
 * This is the API of the Logic Mill project
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CreateIndexRequest model module.
* @module model/CreateIndexRequest
* @version 0.0.0
*/
export default class CreateIndexRequest {
    /**
    * Constructs a new <code>CreateIndexRequest</code>.
    * @alias module:model/CreateIndexRequest
    * @class
    * @param dimensions {Number} 
    */

    constructor(dimensions) {
        
        
        this['dimensions'] = dimensions;
        
    }

    /**
    * Constructs a <code>CreateIndexRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CreateIndexRequest} obj Optional instance to populate.
    * @return {module:model/CreateIndexRequest} The populated <code>CreateIndexRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateIndexRequest();
                        
            
            if (data.hasOwnProperty('dimensions')) {
                obj['dimensions'] = ApiClient.convertToType(data['dimensions'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} dimensions
    */
    'dimensions' = undefined;




}
