/**
 * Logic Mill Api
 * This is the API of the Logic Mill project
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The SearchRequest model module.
* @module model/SearchRequest
* @version 0.0.0
*/
export default class SearchRequest {
    /**
    * Constructs a new <code>SearchRequest</code>.
    * @alias module:model/SearchRequest
    * @class
    * @param keyword {String} 
    */

    constructor(keyword) {
        
        
        this['keyword'] = keyword;
        
    }

    /**
    * Constructs a <code>SearchRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SearchRequest} obj Optional instance to populate.
    * @return {module:model/SearchRequest} The populated <code>SearchRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchRequest();
                        
            
            if (data.hasOwnProperty('keyword')) {
                obj['keyword'] = ApiClient.convertToType(data['keyword'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} keyword
    */
    'keyword' = undefined;




}
