/**
 * Logic Mill Api
 * This is the API of the Logic Mill project
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DocWrapper from './DocWrapper';

/**
* The SimilarityRequest model module.
* @module model/SimilarityRequest
* @version 0.0.0
*/
export default class SimilarityRequest {
    /**
    * Constructs a new <code>SimilarityRequest</code>.
    * @alias module:model/SimilarityRequest
    * @class
    * @param data {module:model/DocWrapper} 
    */

    constructor(data) {
        
        
        this['data'] = data;
        
    }

    /**
    * Constructs a <code>SimilarityRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SimilarityRequest} obj Optional instance to populate.
    * @return {module:model/SimilarityRequest} The populated <code>SimilarityRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SimilarityRequest();
                        
            
            if (data.hasOwnProperty('data')) {
                obj['data'] = DocWrapper.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/DocWrapper} data
    */
    'data' = undefined;




}
