/**
 * Logic Mill Api
 * This is the API of the Logic Mill project
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LogicMillApi);
  }
}(this, function(expect, LogicMillApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LogicMillApi.DocWrapper();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DocWrapper', function() {
    it('should create an instance of DocWrapper', function() {
      // uncomment below and update the code to test DocWrapper
      //var instane = new LogicMillApi.DocWrapper();
      //expect(instance).to.be.a(LogicMillApi.DocWrapper);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new LogicMillApi.DocWrapper();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new LogicMillApi.DocWrapper();
      //expect(instance).to.be();
    });

    it('should have the property document (base name: "document")', function() {
      // uncomment below and update the code to test the property document
      //var instane = new LogicMillApi.DocWrapper();
      //expect(instance).to.be();
    });

    it('should have the property documentParts (base name: "documentParts")', function() {
      // uncomment below and update the code to test the property documentParts
      //var instane = new LogicMillApi.DocWrapper();
      //expect(instance).to.be();
    });

  });

}));
