/**
 * Logic Mill Api
 * This is the API of the Logic Mill project
 *
 * OpenAPI spec version: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import BulkDocumentRequest from './model/BulkDocumentRequest';
import BulkSaveDocumentRequest from './model/BulkSaveDocumentRequest';
import CreateIndexRequest from './model/CreateIndexRequest';
import DocVectorWrapper from './model/DocVectorWrapper';
import DocWrapper from './model/DocWrapper';
import HTTPValidationError from './model/HTTPValidationError';
import MetadataRequest from './model/MetadataRequest';
import SearchRequest from './model/SearchRequest';
import SimilarityQueryRequest from './model/SimilarityQueryRequest';
import SimilarityRequest from './model/SimilarityRequest';
import ValidationError from './model/ValidationError';
import VectorRequest from './model/VectorRequest';
import DefaultApi from './api/DefaultApi';

/**
* This_is_the_API_of_the_Logic_Mill_project.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var LogicMillApi = require('index'); // See note below*.
* var xxxSvc = new LogicMillApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new LogicMillApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new LogicMillApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new LogicMillApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BulkDocumentRequest model constructor.
     * @property {module:model/BulkDocumentRequest}
     */
    BulkDocumentRequest,

    /**
     * The BulkSaveDocumentRequest model constructor.
     * @property {module:model/BulkSaveDocumentRequest}
     */
    BulkSaveDocumentRequest,

    /**
     * The CreateIndexRequest model constructor.
     * @property {module:model/CreateIndexRequest}
     */
    CreateIndexRequest,

    /**
     * The DocVectorWrapper model constructor.
     * @property {module:model/DocVectorWrapper}
     */
    DocVectorWrapper,

    /**
     * The DocWrapper model constructor.
     * @property {module:model/DocWrapper}
     */
    DocWrapper,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The MetadataRequest model constructor.
     * @property {module:model/MetadataRequest}
     */
    MetadataRequest,

    /**
     * The SearchRequest model constructor.
     * @property {module:model/SearchRequest}
     */
    SearchRequest,

    /**
     * The SimilarityQueryRequest model constructor.
     * @property {module:model/SimilarityQueryRequest}
     */
    SimilarityQueryRequest,

    /**
     * The SimilarityRequest model constructor.
     * @property {module:model/SimilarityRequest}
     */
    SimilarityRequest,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
     * The VectorRequest model constructor.
     * @property {module:model/VectorRequest}
     */
    VectorRequest,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
